version: '3.9'
services:
  api:
    build:
      context: ./deployment/docker
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/config/.env
  auth:
    build:
      context: ./auth
    environment:
      - MFA_SECRET=supersecret
